sudo: false
language: node_js
node_js:
  - '8'
before_install:
  - openssl aes-256-cbc -K $encrypted_97d432d3ed20_key -iv $encrypted_97d432d3ed20_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 106.12.140.131\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
  - yarn install --production
script:
  - tar -zcvf ../release.tgz .
after_script:
  - scp -o stricthostkeychecking=no -P $PORT -r public/* root@106.12.140.131:/root
