@domain = http://127.0.0.1:7001

### goods Create
POST {{domain}}/api/goods/create HTTP/1.1
content-type: application/json

{
  "name": "健力宝",
  "price": 5,
  "wholesalePrice": 4,
  "banner": ["https://gradientjoy.com/200x300","https://gradientjoy.com/200x300?id=1","https://gradientjoy.com/200x300?id=2"],
  "imgUrl": "https://gradientjoy.com/200x300",
  "description": "这是推荐的商品",
  "qty": 8,
  "lockQty": 0,
  "unit": "箱",
  "recommend": true
}

### goods List
POST {{domain}}/api/goods/list HTTP/1.1
content-type: application/json

{
  "pageNumber": 1,
  "pageSize": 100
}

### Recommend
Get {{domain}}/api/goods/recommend HTTP/1.1

### goods Update
POST {{domain}}/api/goods/update HTTP/1.1
content-type: application/json

{
  "_id": "5cd39ca728bcd710604ce7ec",
  "name": "jack1"
}

### goods Detail
GEt {{domain}}/api/goods/5cd39ca728bcd710604ce7ec HTTP/1.1

### goods Remove
GEt {{domain}}/api/goods/remove/5cef74c5b1dcc77d80bdd898 HTTP/1.1
