@domain = http://127.0.0.1:7001

### Create
POST {{domain}}/api/order/create HTTP/1.1
content-type: application/json

{
  "user": "5cd390388124fb339807dd53",
  "cart":[
    "5cdbab71b3e7465bb42bdd04",
    "5cdbab71b3e7465bb42bdd05"
  ]
}

### Detail
POST {{domain}}/api/order/list HTTP/1.1
content-type: application/json

{
  "userId": "5cd390388124fb339807dd53",
}

### Update
POST {{domain}}/api/order/update HTTP/1.1
content-type: application/json

{
  "_id": "5cdbac2199bd6945c441ed89",
  "status": 1
}

### Detail
GEt {{domain}}/api/order/5cdbac2199bd6945c441ed89 HTTP/1.1